plugins {
	id "net.fabricmc.fabric-loom" apply false
}

ext.lavaplayerLibraries = {
	final def buildDir = project(":musicplayer-lavaplayer").layout.buildDirectory
	final def libs = buildDir.dir("libs").get().asFile.canonicalPath
	final def dependencies = buildDir.dir("dependencies").get().asFile.canonicalPath
	return "${libs};${dependencies}"
}
