# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=/usr/lib/jvm/java-25

# Minecraft
minecraft_version=26.1.2

# Fabric
loader_version=0.19.3
fabric_api_version=0.152.1+26.1.2

# Mod
mod_version=1.0.0
maven_group=com.naoticaa
mod_id=musicplayerextended

# Dependencies
owo_version=0.13.0+26.1
yacl_version=3.9.0+26.1-fabric
modmenu_version=18.0.0-alpha.8

# Lavaplayer
lavaplayer_version=2.2.4-fix-j8
youtube_source_version=1.18.0
lavadsp_version=0.7.8
lavasrc_version=4.8.1
