pluginManagement {
	repositories {
		maven {
			url = "https://maven.fabricmc.net"
		}
		mavenCentral()
		gradlePluginPortal()
	}
	plugins {
		id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"

		id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT"
	}
}

plugins {
	id "org.gradle.toolchains.foojay-resolver-convention"
}

rootProject.name = "Music-Player"

include("fabric", "musicplayer-lavaplayer-api", "musicplayer-lavaplayer")
